### PR TITLE
Back end

### PR DESCRIPTION
**Pull request by codehass**
# Back end app

Hello 🖐 CR, In this pull request :

- [ ] Create a new Rails API app called 'hello-rails-back-end'.
- [ ] Initialize your project with Git.
- [ ] Make sure that your project has a Postgres database set up.
- [ ] Create a table for storing your messages and create 5 different greetings.
- [ ] Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and rails route).

- [Front end pull request](https://github.com/codehass/hello-react-front-end/compare/front-end?expand=1)

Thank you for reviewing this pull request 😁

### CODE REVIEW

**Review by danmainah — CHANGES_REQUESTED** [review]
Hi @codehass , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a future features section in the readme file for your backend app, kindly add a future features section that contains 1 - 3 features you intend to implement in future

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by codehass** [comment]
Hi @danmainah thank you for your effort 👍 
- Can you please give me some examples of future features that this app can have ?
Thank you

**Review by ridwanediallo — CHANGES_REQUESTED** [review]
# Changes Required ♻️
## Hi @codehass , 
AlmostThereReachGIF

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- You readme file looks professional. ✔


## Required Changes ♻️

- [ ] Hello there, @codehass. excellent work :clap: . Your API is functioning normally and is returning a randum greeting. However, at the front-end, we cannot access that randum greeting because you are currently unable to communicate with a front end, i.e. send data to the front end. So, after spending some time going through your code to see what the problem might be, I discovered that there is something we should address first, which is handling the **Cross-Origin Resource** **CORS** for short.
**CORS** is used to enable our API to accept cross-origin AJAX requests. 👍️

To correct this and ensure that our API can handle AJAX requests, please do the following:
1. In your rails API open the **config** folder and look for the **initializers** folder.
2. In the **initializers** folder open the file named **cors.rb**
3. In the **cors.rb** file uncomment the code in line **8** to line **16**
4. after uncomment the code in line **8** to line **16** where you **origins** replace the string ''example.com'' by an ''*''
5. Finaly restart your server. You are all set. :rocket: 

#### Take a look at the screenshot below to see how I did it
Screenshot from 2023-05-05 21-13-07

#### I hope this helps 😊


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Hassan,  

Your project is complete!🏁 Great job for nailing it! There is nothing else to say other than... it's time to merge it 🍾 Congratulations!  🎉 💯 🌟 

## Highlights 🎯 
🎲  React frontend connects correctly to Rails API backend
🎲  Random greetings are generated correctly 

Cheers..Happy coding! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
